name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: âš¡ Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo
      - name: Install ARM GCC toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi
      - name: Set permissions
        run: chmod +x d
      - name: Load sources
        run: ./d download-all
      - name: Install Rust targets
        run: rustup target add thumbv8m.main-none-eabihf thumbv7em-none-eabi thumbv6m-none-eabi
      - name: Run tests
        run: cargo test --workspace --all-targets
      - name: Run build
        run: cargo run --release --bin stm32-bindings-gen
      - name: Check generated crate targets
        run: |
          cd build/stm32-bindings
          for target in thumbv7em-none-eabi thumbv6m-none-eabi; do
            echo "Checking target $target"
            cargo check --target "$target" --no-default-features --features pac
          done
      - name: Run package build
        run: |
          cd build/stm32-bindings
          export CARGO_BUILD_TARGET=thumbv8m.main-none-eabihf
          cargo fix --lib -p stm32-bindings --allow-no-vcs
          cargo build
          cargo package
          ls target/package
      - name: Upload package build
        uses: actions/upload-artifact@v4
        with:
          name: crate
          path: build/stm32-bindings/target/package/*.crate
